//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourManagementSystem.Global
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTER
    {
        public int REGISTER_ID { get; set; }
        public string REGISTER_NAME { get; set; }
        public string REGISTER_ADDRESS { get; set; }
        public string REGISTER_PHONE_NUMBER { get; set; }
        public string REGISTER_EMAILL { get; set; }
        public string REGISTER_DETAIL { get; set; }
        public int TOUR_ID { get; set; }
    
        public virtual TOUR TOUR { get; set; }
    }
}
