//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourManagementSystem.Global
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOUR_LOCATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TOUR_LOCATION()
        {
            this.TOUR_LOCATION_DETAIL = new HashSet<TOUR_LOCATION_DETAIL>();
        }
    
        public int TOUR_LOCATION_ID { get; set; }
        public string TOUR_LOCATION_NAME { get; set; }
        public int PLACE_ID { get; set; }
        public string TOUR_LOCATION_ADDRESS { get; set; }
        public string TOUR_LOCATION_DESCRIPTION { get; set; }
    
        public virtual PLACE PLACE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOUR_LOCATION_DETAIL> TOUR_LOCATION_DETAIL { get; set; }
    }
}
