//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourManagementSystem.Global
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOUR_MISSION
    {
        public int TOUR_MISSION_ID { get; set; }
        public string TOUR_MISSION_DESCRIPTION { get; set; }
        public string TOUR_MISSION_RESPONSIBILITY { get; set; }
        public int TOUR_INFORMATION_ID { get; set; }
        public int TOUR_STAFF_ID { get; set; }
    
        public virtual TOUR_INFORMATION TOUR_INFORMATION { get; set; }
        public virtual TOUR_STAFF TOUR_STAFF { get; set; }
    }
}
