//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourManagementSystem.Global
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOUR_TIME
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TOUR_TIME()
        {
            this.TRAVEL_GROUP = new HashSet<TRAVEL_GROUP>();
        }
    
        public int TOUR_TIME_ID { get; set; }
        public Nullable<System.DateTime> TOUR_TIME_DEPARTMENT_DATE { get; set; }
        public Nullable<System.DateTime> TOUR_TIME_END_DATE { get; set; }
        public int TOUR_ID { get; set; }
    
        public virtual TOUR TOUR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRAVEL_GROUP> TRAVEL_GROUP { get; set; }
    }
}
