//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourManagementSystem.Global
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOUR_HOTEL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TOUR_HOTEL()
        {
            this.TOUR_HOTEL_DETAIL = new HashSet<TOUR_HOTEL_DETAIL>();
        }
    
        public int TOUR_HOTEL_ID { get; set; }
        public string TOUR_HOTEL_NAME { get; set; }
        public string TOUR_HOTEL_ADDRESS { get; set; }
        public string TOUR_HOTEL_PHONE_NUMBER { get; set; }
        public string TOUR_HOTEL_IS_RESTAURANT { get; set; }
        public Nullable<double> TOUR_HOTEL_PRICE { get; set; }
        public string TOUR_HOTEL_TYPE { get; set; }
        public string TOUR_HOTEL_DESCRIPTION { get; set; }
        public string TOUR_HOTEL_EMAIL { get; set; }
        public int PLACE_ID { get; set; }
        public Nullable<bool> TOUR_HOTEL_DELETE { get; set; }
    
        public virtual PLACE PLACE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOUR_HOTEL_DETAIL> TOUR_HOTEL_DETAIL { get; set; }
    }
}
