//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourManagementSystem.Global
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOUR_HARD_PRICE
    {
        public int TOUR_HARD_PRICE_ID { get; set; }
        public Nullable<double> TOUR_HARD_PRICE_COST { get; set; }
        public string TOUR_HARD_PRICE_CONTENT { get; set; }
        public string TOUR_HARD_PRICE_DESCRIPTION { get; set; }
    }
}
