//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourManagementSystem.Global
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAVEL_COST
    {
        public int TRAVEL_COST_ID { get; set; }
        public Nullable<double> TOTAL_HOTEL_COST { get; set; }
        public Nullable<double> TOTAL_MEAL_COST { get; set; }
        public Nullable<double> TOTAL_TRANSPORT_COST { get; set; }
        public Nullable<double> ANOTHER_COST { get; set; }
        public int TRAVEL_GROUP_ID { get; set; }
    
        public virtual TRAVEL_GROUP TRAVEL_GROUP { get; set; }
    }
}
