//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourWeb.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOUR_ACCOUNT
    {
        public int TOUR_ACCOUNT_ID { get; set; }
        public string TOUR_ACCOUNT_NAME { get; set; }
        public string TOUR_ACCOUNT_PASSWORD { get; set; }
        public int TOUR_STAFF_ID { get; set; }
    
        public virtual TOUR_STAFF TOUR_STAFF { get; set; }
    }
}
