//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourWeb.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOUR_PRICE
    {
        public int TOUR_PRICE_ID { get; set; }
        public Nullable<double> TOUR_PRICE_COST_TOTAL { get; set; }
        public Nullable<double> TOUR_PRICE_COST_HOTEL { get; set; }
        public Nullable<double> TOUR_PRICE_COST_TRANSPORT { get; set; }
        public Nullable<double> TOUR_PRICE_COST_SERVICE { get; set; }
        public string TOUR_PRICE_NOTE { get; set; }
        public int TOUR_INFORMATION_ID { get; set; }
    
        public virtual TOUR_INFORMATION TOUR_INFORMATION { get; set; }
    }
}
