//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOUR_MISSION
    {
        public int TOUR_MISSION_ID { get; set; }
        public Nullable<System.DateTime> TOUR_MISSION_TIME { get; set; }
        public string TOUR_MISSION_RESPONSIBILITY { get; set; }
        public int TRAVEL_GROUP_ID { get; set; }
        public int TOUR_STAFF_ID { get; set; }
    
        public virtual TOUR_STAFF TOUR_STAFF { get; set; }
        public virtual TRAVEL_GROUP TRAVEL_GROUP { get; set; }
    }
}
