//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAVEL_COST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRAVEL_COST()
        {
            this.TRAVEL_GROUP = new HashSet<TRAVEL_GROUP>();
        }
    
        public int TRAVEL_COST_ID { get; set; }
        public Nullable<double> TOTAL_HOTEL_COST { get; set; }
        public Nullable<double> TOTAL_MEAL_COST { get; set; }
        public Nullable<double> TOTAL_TRANSPORT_COST { get; set; }
        public Nullable<double> ANOTHER_COST { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRAVEL_GROUP> TRAVEL_GROUP { get; set; }
    }
}
